### ISSUE TITLE
Duda con resolución clase 4

### ISSUE THREAD

**Issue by mcnanton** [mcnanton/DMKDD-AID#1]
¿Alguien podría explicar, en la resolución del ejercicio 2 (Escribir la función que calcula el módulo de un número real), para qué sirve el argumento "fijo"?
`
modulo <- function(num, fijo=0){
  return(abs(num)+fijo)
}
`
Así lo sumo al script como comentario. Gracias!

**Comment by Ignacio-Ibarra** [comment]
Es simplemente la función módulo f(x ) = |x| + c. Cuya constante C genera un efecto fijo. That's all

**Comment by Ignacio-Ibarra** [comment]
La función módulo más básica del módulo de un número es f(x) = |x|. Yo agregué una constante que el argumento "fijo"
